const accesorios = {
  results: [
    {
      accesorio: "Camara de reversa",
      cantidad: "5",
      precio: "60000",
      url: "",
    },

    {
      accesorio: "alarma",
      cantidad: "10",
      precio: "120000",
      url: "",
    },
    {
      accesorio: "sensor estacionamiento",
      cantidad: "20",
      precio: "15000",
      url: "",
    },
    {
      accesorio: "bloqueo volante",
      cantidad: "15",
      precio: "20000",
      url: "",
    },
    {
      accesorio: "kit primeros auxilios",
      cantidad: "30",
      precio: "25000",
      url: "",
    },
    {
      accesorio: "extintor",
      cantidad: "40",
      precio: "10000",
      url: "",
    },
    {
      accesorio: "Cinturon mascotas",
      cantidad: "8",
      precio: "45000",
      url: "",
    },
    {
      accesorio: "cadenas",
      cantidad: "22",
      precio: "16000",
      url: "",
    },
    {
      accesorio: "luces antiniebla",
      cantidad: "14",
      precio: "25000",
      url: "",
    },
    {
      accesorio: "GPS",
      cantidad: "30",
      precio: "300000",
      url: "",
    },

    {
      accesorio: "cubreasientos",
      cantidad: "30",
      precio: "30000",
      url: "",
    },
    {
      accesorio: "alfombrilla",
      cantidad: "15",
      precio: "150000",
      url: "",
    },
    {
      accesorio: "Cargador USB",
      cantidad: "30",
      precio: "16000",
      url: "",
    },
    {
      accesorio: "Refrigerador portatil",
      cantidad: "5",
      precio: "70000",
      url: "",
    },
    {
      accesorio: "organizador de maletero",
      cantidad: "10",
      precio: "30000",
      url: "",
    },
    {
      accesorio: "retrovisor",
      cantidad: "8",
      precio: "250000",
      url: "",
    },
    {
      accesorio: "soporte celular",
      cantidad: "20",
      precio: "7000",
      url: "",
    },
    {
      accesorio: "protetor parabrisas",
      cantidad: "10",
      precio: "25000",
      url: "",
    },
    {
      accesorio: "asiento masajeador",
      cantidad: "5",
      precio: "280000",
      url: "",
    },
    {
      accesorio: "Difunsor de aromas",
      cantidad: "22",
      precio: "15000",
      url: "",
    },

    {
      accesorio: "Aleron Trasero",
      cantidad: "8",
      precio: "200000",
      url: "",
    },
    {
      accesorio: "Tapas valvulas personalizadas",
      cantidad: "10",
      precio: "25000",
      url: "",
    },
    {
      accesorio: "vinilos decorativos",
      cantidad: "10",
      precio: "32000",
      url: "",
    },
    {
      accesorio: "llantas de aleacion",
      cantidad: "20",
      precio: "450000",
      url: "",
    },
    {
      accesorio: "volante deportivo",
      cantidad: "9",
      precio: "60000",
      url: "",
    },
    {
      accesorio: "faros led",
      cantidad: "7",
      precio: "25000",
      url: "",
    },
    {
      accesorio: "pedales de aluminio",
      cantidad: "6",
      precio: "40000",
      url: "",
    },
    {
      accesorio: "emblemas",
      cantidad: "7",
      precio: "28000",
      url: "",
    },
    {
      accesorio: "manijas cromadas",
      cantidad: "20",
      precio: "25000",
      url: "",
    },
    {
      accesorio: "faros led",
      cantidad: "7",
      precio: "25000",
      url: "",
    },
    {
      accesorio: "pintura calipers",
      cantidad: "2",
      precio: "36000",
      url: "",
    },

    {
      accesorio: "filtro de aire",
      cantidad: "5",
      precio: "33000",
      url: "",
    },
    {
      accesorio: "escape deportivo",
      cantidad: "3",
      precio: "258000",
      url: "",
    },
    {
      accesorio: "chip de rendimiento",
      cantidad: "4",
      precio: "155000",
      url: "",
    },
    {
      accesorio: "barra estabilizadora",
      cantidad: "6",
      precio: "70000",
      url: "",
    },
    {
      accesorio: "amortiguadores reforzados",
      cantidad: "12",
      precio: "195000",
      url: "",
    },
    {
      accesorio: "pastillas de freno",
      cantidad: "40",
      precio: "12000",
      url: "",
    },
    {
      accesorio: "radiador mejorado",
      cantidad: "4",
      precio: "288000",
      url: "",
    },
    {
      accesorio: "filtro altoflujo de aceite",
      cantidad: "11",
      precio: "16000",
      url: "",
    },
    {
      accesorio: "Turbo",
      cantidad: "7",
      precio: "244000",
      url: "",
    },
    {
      accesorio: "suspension ajustable",
      cantidad: "16",
      precio: "186000",
      url: "",
    },
  ],
};
